sudo: false
language: php
php:
  - 5.3
cache:
  directories:
    - $HOME/.composer/cache
install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install  --prefer-dist --no-interaction
script: php tests/wire.test.php --verbose
